#!/usr/bin/env python
# SPDX-License-Identifier: GPL-3.0-or-later
"""Write lib/galileo_e1_codes.h from python/gpsrx/data/galileo_e1_codes.npz: the E1-B and E1-C
primary codes, PRN 1..36, 4092 chips each, as hex strings (4 chips per character, first chip in
the high bit; bit 1 = chip -1). The C++ Channel carries its own copy so a GRC canvas needs no
Python side to run Galileo."""
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
NPZ = os.path.join(HERE, "..", "python", "gpsrx", "data", "galileo_e1_codes.npz")
OUT = os.path.join(HERE, "..", "lib", "galileo_e1_codes.h")


def to_hex(code):
    bits = (np.asarray(code) < 0).astype(np.uint8)
    assert len(bits) == 4092
    return "".join(f"{int(bits[i] << 3 | bits[i + 1] << 2 | bits[i + 2] << 1 | bits[i + 3]):X}" for i in range(0, 4092, 4))


def main():
    d = np.load(NPZ)
    lines = ["/* -*- c++ -*- */", "/* Generated by util/make_e1_codes_h.py from python/gpsrx/data/galileo_e1_codes.npz",
             " * (Galileo OS SIS ICD Annex C, via gnss-sdr's Galileo_E1.h, GPL-3). Do not edit. */",
             "#ifndef INCLUDED_GPSRX_GALILEO_E1_CODES_H", "#define INCLUDED_GPSRX_GALILEO_E1_CODES_H", "",
             "namespace gr {", "namespace gpsrx {", "",
             "// PRN 1..36, 4092 chips as 1023 hex characters, first chip in the high bit, bit 1 = chip -1"]
    for comp in ("b", "c"):
        lines.append(f"static const char* const GALILEO_E1{comp.upper()}_HEX[36] = {{")
        for prn in range(1, 37):
            lines.append(f'    "{to_hex(d[f"{comp}{prn}"])}",')
        lines.append("};")
        lines.append("")
    lines += ["} // namespace gpsrx", "} // namespace gr", "", "#endif", ""]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
