/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(channel_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gpsrx/channel_cc.h>
// pydoc.h is automatically generated in the build directory
#include <channel_cc_pydoc.h>

void bind_channel_cc(py::module& m)
{

    using channel_cc    = gr::gpsrx::channel_cc;


    py::class_<channel_cc, gr::block, gr::basic_block,
        std::shared_ptr<channel_cc>>(m, "channel_cc", D(channel_cc))

        .def(py::init(&channel_cc::make),
           D(channel_cc,make)
        )
        



        ;




}








